{
 "title": "Coms Processes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "# Process",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) FROM process_instance"
    }
   ]
  },
  {
   "title": "# Activities",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) FROM process_activity"
    }
   ]
  },
  {
   "title": "# Tasks",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) FROM task_instance"
    }
   ]
  },
  {
   "title": "# Open Tasks",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) FROM task_instance where status = 'NEW'"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT id, code, status, created, updated FROM process_instance order by created desc"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT id, name, status, assigned_user, activity_id, process_id, description from task_instance"
    }
   ]
  },
  {
   "title": "Process Activities",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT id, instance_id, event, type, description, start, finish FROM process_activity order by id desc"
    }
   ]
  },
  {
   "title": "Avg. Execution Time By Activity",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT  description as activity, avg(finish - start) as avg_span FROM process_activity where finish is not null group by description"
    }
   ]
  }
 ]
}