apiVersion: apps/v1
kind: Deployment
metadata:
  name: coms-api-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coms-api-flow
  template:
    metadata:
      labels:
        app: coms-api-flow
    spec:
      containers:
        - name: coms-api-flow
          image: sibendu/coms-api-flow
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              value: dev
          imagePullPolicy: Always

      initContainers:
      - name: init-coms-api-flow
        image: sibendu/initflow
        env:
          - name: DB_HOST
            value: postgres
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: admin
          - name: PGPASSWORD
            value: admin123
          - name: DB_NAME
            value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: coms-api-flow
spec:
  type: NodePort
  selector:
    app: coms-api-flow
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080     