apiVersion: apps/v1
kind: Deployment
metadata:
  name: coms-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coms-ui
  template:
    metadata:
      labels:
        app: coms-ui
    spec:
      containers:
      - name: coms-ui
        image: sibendu/coms-ui
        ports:
          - containerPort: 8080
        env:
          - name: coms.service.uri
            value: "http://coms-api-flow:8080"
          - name: coms.userservice.uri
            value: "http://coms-api-user:8080"
        imagePullPolicy: Always
      imagePullSecrets:
          - name: gitlabregcred
---
apiVersion: v1
kind: Service
metadata:
  name: coms-ui
spec:
  selector:
    app: coms-ui
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
  type: NodePort
